#
# EcoArmor
# by Auxilor
#

discover-recipes: true # If all recipes should be automatically discovered.
update-item-names: true # If item names should be updated to match config (disable to allow renaming armor pieces in anvils)
update-leather-colors: true # If leather colors should be updated to match config
advanced-lore-only: false # If advanced armor should only show the advanced lore
